### ISSUE TITLE
Nocode and perfect-lang similarities

### ISSUE THREAD

**Issue by TechWiz-3** [Just-Moh-it/perfect-lang#2]
Not to spoil the fun, but this repo seems very similar to https://github.com/kelseyhightower/nocode

**Comment by Just-Moh-it** [comment]
Yeah, this was inspired, but the idea is different... this is not ditching code for a no-code platform, but rather embracing the beauty of coding without errors... it's just witticism anyway

**Comment by TechWiz-3** [comment]
🔥
